package ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2017-01-09T20:11:32.085+03:00
 * Generated source version: 3.1.9
 * 
 */
@WebServiceClient(name = "PersonsService", 
                  wsdlLocation = "file:/home/vietto/IdeaProjects/wsclient/src/main/java/ws/persons.wsdl",
                  targetNamespace = "http://inno.ru/") 
public class PersonsService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://inno.ru/", "PersonsService");
    public final static QName PersonsPort = new QName("http://inno.ru/", "PersonsPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/vietto/IdeaProjects/wsclient/src/main/java/ws/persons.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PersonsService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/vietto/IdeaProjects/wsclient/src/main/java/ws/persons.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PersonsService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PersonsService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonsService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public PersonsService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PersonsService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PersonsService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns PersonsService
     */
    @WebEndpoint(name = "PersonsPort")
    public PersonsService getPersonsPort() {
        return super.getPort(PersonsPort, PersonsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonsService
     */
    @WebEndpoint(name = "PersonsPort")
    public PersonsService getPersonsPort(WebServiceFeature... features) {
        return super.getPort(PersonsPort, PersonsService.class, features);
    }

}
