
package ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2017-01-09T20:11:31.916+03:00
 * Generated source version: 3.1.9
 * 
 */
public final class PersonsService_PersonsPort_Client {

    private static final QName SERVICE_NAME = new QName("http://inno.ru/", "PersonsService");

    private PersonsService_PersonsPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PersonsService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        PersonsService_Service ss = new PersonsService_Service(wsdlURL, SERVICE_NAME);
        PersonsService port = ss.getPersonsPort();  
        
        {
        System.out.println("Invoking addPerson...");
        ws.Person _addPerson_awesomePerson = null;
        ws.Person _addPerson__return = port.addPerson(_addPerson_awesomePerson);
        System.out.println("addPerson.result=" + _addPerson__return);


        }
        {
        System.out.println("Invoking getAwesomePersons...");
        ws.PersonArray _getAwesomePersons__return = port.getAwesomePersons();
        System.out.println("getAwesomePersons.result=" + _getAwesomePersons__return);


        }

        System.exit(0);
    }

}
